baseURL = 'https://civicpassport.com/'
languageCode = 'en-us'
title = 'Civic Passport'
theme = 'PaperMod'

# Enable for better URLs
[permalinks]
  posts = '/:year/:month/:day/:slug/'

[params]
  env = "production"
  description = "Open Borders for Curious Minds"
  author = "Daniel Jeskey"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  disableSpecial1stPost = false
  hidemeta = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "Civic Passport"
    Content = "Open Borders for Curious Minds"

  [[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/civicpassport.bsky.social"

  [[params.socialIcons]]
    name = "mastodon"
    url = "https://mastodon.social/@jeskey"

  [[params.socialIcons]]
    name = "threads"
    url = "https://threads.net/@dannyjeskey"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/profile.php?id=61569918777600"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
